version: '2'
services:
  couchbase:
    container_name: couchbase_container
    build: ./couchbase
    volumes:
      - /opt/couchbase/var/lib/couchbase/data
    image: ramazanzor19/couchbase
    ports:
      - "8091-8093:8091-8093"
      - "11210:11210"
  todoapp:
    container_name: todoapp
    image: ramazanzor19/todoapp
    ports:
      - 8080:8080
    environment:
      - SPRING_COUCHBASE_CONNECTION=couchbase://couchbase_container
      - SPRING_COUCHBASE_BUCKET=note
      - SPRING_COUCHBASE_USERNAME=ramazan
      - SPRING_COUCHBASE_PASSWORD=ramo123
    restart: always
    depends_on:
      - couchbase
